name: Build and Upload IPA
on:
  push:
    branches:
      - '**'
jobs:
  build:
    runs-on: macos-15
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Build App
        run: |
          xcodebuild -project StoreControl.xcodeproj -scheme StoreControl -configuration Release -derivedDataPath build/DerivedDataApp -destination 'generic/platform=iOS Simulator' CODE_SIGNING_ALLOWED=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO clean build
          mkdir -p build
          cp -r build/DerivedDataApp/Build/Products/Release-iphonesimulator/StoreControl.app ./build/
          cd build
          zip -r StoreControl.ipa StoreControl.app

      - name: Upload IPA Artifact
        uses: actions/upload-artifact@v4
        with:
          name: StoreControl.ipa
          path: ./build/StoreControl.ipa
